## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np

In [11]:
x = np.random.randint(1, 11, (3,3))
y = np.random.randint(11, 22, (3,3))
print(x.dot(y))

[[200 222 198]
 [208 230 203]
 [287 308 283]]


## Write a NumPy program to compute the determinant of a given square array

In [14]:
np.sqrt(x)

array([[2.64575131, 1.73205081, 1.73205081],
       [2.64575131, 2.        , 1.41421356],
       [2.82842712, 2.        , 2.64575131]])

## Write a NumPy program to compute the cross product of two given vectors

In [21]:
n = np.random.randint(7, 34, (3,3))
m = np.random.randint(20, 45, (3,3))

np.cross(n,m)

array([[ 560, -649,   45],
       [ 485, -241, -158],
       [-220,  805, -250]])

## Write a NumPy program to compute the condition number of a given matrix

## Write a NumPy program to compute the inverse of a given matrix

In [18]:
A = np.random.randint(1, 11, (3,3))
A


array([[ 5,  5,  8],
       [ 8,  4, 10],
       [ 7,  2,  3]])

In [19]:
print(np.linalg.inv(A))  


[[-0.08510638  0.0106383   0.19148936]
 [ 0.4893617  -0.43617021  0.14893617]
 [-0.12765957  0.26595745 -0.21276596]]
